[package]
name = "mumia-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
gloo-console = "0.2"
js-sys = "0.3"
yew = "0.19"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
serde = "1.0.136"
reqwasm = "0.5.0"
log = "0.4.6"
wasm-logger = "0.2.0"
serde_json = "1.0"
futures = "0.3.21"